name: millimore
description: The Creator Economy for Traders
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  camera: ^0.11.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  web_socket_channel: ^3.0.3
  image_picker: ^1.1.2
  webview_flutter: ^4.10.0
  qr_flutter: ^4.1.0
  share_plus: ^10.1.2
  path_provider: ^2.1.4
  gal: ^2.3.0
  video_player: ^2.9.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  haishin_kit: ^0.16.0
  audio_session: ^0.1.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  image_path: "assets/icon/millimore_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  background_color_ios: "#0B1120"
